# src/main/resources/plugin.yml
name: BaimoSurvivalPerm
version: 1.0
main: top.baimoqilin.BaimoSurvivalPerm
commands:
  baimosp:
    description: BaimoSurvivalPerm command
    usage: /baimosp <reload|add> [player-name]
    permission: baimosp.admin
permissions:
  baimosp.admin:
    description: Allows to use /baimosp command
    default: op

