name: Windows Builds

on:
  push:
    branches: [ "master", "dev-ui"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build with Pyinstaller
      run: pyinstaller --onedir --add-data "projects;projects" --add-data "logs;logs" console.py
    - name: Zip build result
      run: |
        cd dist
        zip -r console.zip console
    - name: Upload the zip file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-console
        path: dist/console.zip
